### ISSUE TITLE
storage: crafting & provisioning

### ISSUE THREAD

**Issue by kukeiko** [kukeiko/squirtle-cc-tweaked#20]
## What
The user should be able to retrieve items from the storage. If it doesn't have enough, it should craft them. If it doesn't have enough ingredients, the player is notified about it so they can gather and add them to the storage.

## Todo
- [x] dispenser should support crafting
- [x] allow crafting more than available
- [x] show some form of progress
- [x] notify player of missing ingredients
- [x] dispenser should return to item list immediately instead of waiting for transfer/craft to be complete
- [x] allow adding recipes to the storage system
- [ ] support parallel provide-items/craft-items/allocate-ingredients tasks so that total missing ingredients are shown (but having only one io-crafter is fine)
  - to be done in #24
- [x] allocate task buffers based on required slot count
- [ ] ensure task cleanup on errors
  - to be done in #24
- [x] bug: because storages are cached, if the player issues a craft task and takes out ingredients, the storage system may accidentally remove a stack completely.
- [x] bug: remaining ingredients from io-crafter should be put into storage (currently, they end up in the dispenser stash)
- [x] bug: allocate-ingredients sometimes gets stuck when ingredients are missing but then supplied by the players. I have been able to reproduce this issue somewhat consistently. It can be fixed by restarting the storage & storage-workers.
  - I've pushed a potential fix, first two crafts worked without issue, so let's see
  - [update]: haven't encountered the issue for a while now, so looks good
- [x] bug: io-crafter crashed when trying to craft redstone repeaters and sticks were missing in the storage, as it couldn't fetch the item-details for that
  - this can only happen a craft was issued, player completely removes ingredients from storage, and then storage gets rebooted. while not ideal, that is a fringe edge case that I'm going to ignore for now
- [x] bug: the reported number of items transferred can be higher than the ones wanted in case they are being crafted, e.g.: want 1x stick, crafts 4x sticks => shows 4/1

**Comment by kukeiko** [comment]
We have dispensing & crafting working without too many issues! Improvements will be done in #24.
