### ISSUE TITLE
io-network: rework furnaces

### ISSUE THREAD

**Issue by kukeiko** [kukeiko/squirtle-cc-tweaked#21]
## What
Rework furnace code so that it fills up furnaces with any smeltable items provided by the player (as opposed to only filling up existing stacks in furnaces).

- the player provides fuel & smeltable items in a dedicated furnace input chest
- the io-network distributes those items into any connected furnaces
- the io-network distributes smelted items into a dedicated furnace output chest
- empty buckets are put into storage chests (so that lava turtles can suck them out from their bottom storage chest)

## Notes
This will break existing furnace logic - which is fine as this new io-network version is used in a completely new base, and the code of the old base won't be updated.

## Todo
- [x] move items from furnace input chests into furnaces
- [x] move items from furnaces to furnace output chests
- [x] move empty buckets to storages
- [x] somehow prevent spamming all furnaces with 1x type of item; e.g. a cobblestone generator should not block player provided smeltables
